### ISSUE TITLE
Disabling dispatch

### ISSUE THREAD

**Issue by kokujin** [kethinov/page-express-mapper#5]
I was trying to follow the page.js example here:
https://github.com/visionmedia/page.js/blob/master/examples/server/app.js

I noticed that the dispatch setting could not be disabled using:

```
page({ dispatch: false });
```

Is there a way to get the server to render initial content first when using the express-mapper plugin?

Thanks

**Comment by kethinov** [comment]
Can you post an example?

Offhand I don't see anything in the plugin that would prevent that from working. All the plugin does really is overload [this method](https://github.com/visionmedia/page.js/blob/4895e378a7080a519390e286a22b02a87a055b10/page.js#L471) which I don't think would stop disabling dispatch from working.
